name: Backend CI/CD with Conditional Tests

on:
  push:
    branches: ["main"]
    tags: ["test-**"]

jobs:
  run-tests:
    name: Run Tests
    if: startsWith(github.ref, 'refs/tags/test-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v3 -> v4 최신 버전으로 업데이트

      - name: Setup Node.js
        uses: actions/setup-node@v4 # v3 -> v4 최신 버전으로 업데이트
        with:
          node-version: "18"
          cache: "npm" # npm ci를 위해 캐시 사용

      - name: Install dependencies
        run: npm ci # npm install 대신 npm ci 사용 권장

      - name: Execute tests
        run: npm test

  build-and-deploy:
    name: Build and Deploy
    needs: run-tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3 # v2 -> v3 최신 버전으로 업데이트
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # v4 -> v5 최신 버전으로 업데이트
        with:
          context: .
          push: true
          tags: jeehokim/allweneedfarm-backend:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # v2 -> v4 최신 버전으로 업데이트
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EC2 instance
        uses: aws-actions/amazon-ssm-send-command@v1
        with:
          instance-ids: ${{ secrets.AWS_EC2_INSTANCE_ID }}
          working-directory: /home/ec2-user/backend
          command: |
            docker-compose pull
            docker-compose up -d --no-deps --build node-app
