# 워크플로우의 이름
name: Pull Request Check

# 워크플로우 실행 조건
on:
  # 'main' 브랜치로 향하는 Pull Request가 생성되거나,
  # 해당 PR에 새로운 코드가 push될 때마다 실행됩니다.
  pull_request:
    branches: ["main"]

jobs:
  # 실행할 작업의 이름
  pr-quality-checks:
    name: PR Quality Checks
    runs-on: ubuntu-latest

    steps:
      # 1. PR에 올라온 최신 코드를 runner로 가져옵니다.
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 프로젝트에서 사용하는 Node.js 버전을 설정합니다.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          # npm install 보다 빠르고 안정적인 npm ci를 위해 캐시를 사용합니다.
          cache: "npm"

      # 3. 의존성을 설치합니다.
      # 'npm ci'는 package-lock.json을 기반으로 정확한 버전의 패키지를 설치하여,
      # CI 환경에서 더 일관되고 빠른 설치를 보장합니다.
      - name: Install dependencies
        run: npm ci

      # 4. 코드 스타일 검사(Linter)를 실행합니다.
      # 이 스크립트는 package.json에 정의되어 있어야 합니다. (아래 추가 설명 참조)
      - name: Run linter
        run: npm run lint

      # 5. 단위/통합 테스트를 실행합니다.
      - name: Run tests
        run: npm test
